spring:
  datasource:
    url: jd bc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: gogo
    password: gogo
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        conectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: A4514D8D1BB4A45AECE67FC3541C8
      expiration: 8640000